#Minecraft server properties
#Mon Mar 02 09:05:23 UTC 2026
view-distance=69
max-build-height=250
server-ip=0.0.0.0
level-seed=
server-port=25565
gamemode=0
enable-command-block=false
allow-nether=true
enable-rcon=true
rcon.port=25575
rcon.password=HellC0re_Rc0n2026!
op-permission-level=4
enable-query=false
generator-settings=
resource-pack=
player-idle-timeout=0
level-name=world
motd=A Minecraft Server
query.port=25565
announce-player-achievements=false
force-gamemode=false
debug=false
hardcore=false
white-list=false
pvp=true
spawn-npcs=true
generate-structures=true
spawn-animals=true
snooper-enabled=true
difficulty=1
network-compression-threshold=256
level-type=DEFAULT
spawn-monsters=true
max-players=250
use-native-transport=true
spawn-protection=0
online-mode=false
allow-flight=false
resource-pack-hash=
max-world-size=29999984
