#Minecraft server properties
#Tue Mar 24 07:58:51 SGT 2026
allow-flight=false
allow-nether=true
announce-player-achievements=false
debug=false
difficulty=1
enable-command-block=false
enable-query=false
broadcast-rcon-to-ops=false
enable-rcon=true
rcon.port=25575
rcon.password=HellC0re_Rc0n2026!
force-gamemode=true
gamemode=2
generate-structures=true
generator-settings=
hardcore=false
level-name=world
level-seed=
level-type=DEFAULT
max-build-height=250
max-players=250
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=-1
online-mode=false
op-permission-level=4
player-idle-timeout=0
pvp=true
query.port=25565
resource-pack=
resource-pack-hash=
server-ip=0.0.0.0
server-port=25565
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
use-native-transport=true
view-distance=10
white-list=false
